### ISSUE TITLE
Support of more recent AC files

### ISSUE THREAD

**Issue by rudolfninja** [nextgis-borsch/lib_opencad#1]
Hi,
Thanks for your work. Could you please answer if there any plans on implementing support of more recent AC file versions, but not only R2000?
Thanks.

**Comment by simgislab** [comment]
Hello, no particular plans as of now.

Our motivation is one of the following:
1. pull-requests
2. projects
3. sponsorship

Right now we have none of the above.

**Comment by rudolfninja** [comment]
Got you. So what the difference between your project and [libopencad](https://github.com/sandyre/libopencad)?

**Comment by simgislab** [comment]
this is more or less the same project, the link you mention is by GSoC student we mentored. We continue the development here.
